use_frameworks!
platform :ios, '11.0'

target 'MMCardView_Example' do
  pod 'MMCardView', :path => '../'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end